# Generated by Django 4.1.1 on 2022-09-23 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=45)),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("review", models.TextField(default="")),
                ("product_info", models.TextField(default="")),
                ("product_brand", models.CharField(max_length=45)),
                ("product_category", models.CharField(max_length=45)),
                ("gender_type", models.CharField(max_length=1)),
                ("available", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="UserTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=45)),
                ("lname", models.CharField(max_length=45)),
                ("address", models.TextField(default="")),
                ("email", models.CharField(max_length=255)),
                ("dob", models.DateField(default=datetime.date.today)),
                ("gender", models.CharField(max_length=10)),
                ("username", models.CharField(max_length=255)),
                ("password", models.BinaryField(max_length=60)),
                ("phone", models.IntegerField(default=0)),
                ("banned_status", models.BooleanField()),
                ("verifiedStatus", models.BooleanField()),
                ("verificationCode", models.PositiveSmallIntegerField()),
                ("lockedStatus", models.BooleanField()),
                ("lockedCounter", models.PositiveSmallIntegerField()),
                ("accountType", models.CharField(default="User", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdDate", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.usertable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDetailsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("size", models.CharField(max_length=5)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.productstable",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.transactiontable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCartTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=45)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.productstable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.usertable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductQuantityTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=5)),
                ("quantity", models.IntegerField(default=0)),
                ("color", models.CharField(max_length=45)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.productstable",
                    ),
                ),
            ],
        ),
    ]
