# Generated by Django 4.1.1 on 2022-10-18 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=45)),
                (
                    "product_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("review", models.TextField(default="")),
                ("product_info", models.TextField(default="")),
                ("product_brand", models.CharField(max_length=45)),
                ("product_category", models.CharField(max_length=45)),
                ("gender_type", models.CharField(max_length=10)),
                ("available", models.CharField(max_length=3)),
                ("status", models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("verify_password", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=255)),
                ("phone", models.IntegerField()),
                ("bannedStatus", models.BooleanField(default=False)),
                ("verifiedStatus", models.BooleanField()),
                ("verificationCode", models.PositiveSmallIntegerField(null=True)),
                ("lockedStatus", models.BooleanField()),
                ("lockedCounter", models.PositiveSmallIntegerField(null=True)),
                ("accountType", models.CharField(default="User", max_length=10)),
                (
                    "unique_id",
                    models.CharField(default="", max_length=255, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDetailsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField(default=datetime.date.today)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=10,
                    ),
                ),
                (
                    "unique_id",
                    models.ForeignKey(
                        db_column="unique_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.usertable",
                        to_field="unique_id",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdDate", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="unique_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.usertable",
                        to_field="unique_id",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionDetailsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("size", models.CharField(max_length=5)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.productstable",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.transactiontable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCartTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=45)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.productstable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="unique_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.usertable",
                        to_field="unique_id",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductQuantityTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=5)),
                ("quantity", models.IntegerField(default=0)),
                ("color", models.CharField(max_length=45)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.productstable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreOrderTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.productstable",
                    ),
                ),
                (
                    "unique_id",
                    models.ForeignKey(
                        db_column="unique_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShoesInvasionApp.usertable",
                        to_field="unique_id",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
