# Generated by Django 4.1.1 on 2022-09-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ShoesInvasionApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="banned_status",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
